### ISSUE TITLE
[BUG] thumbnails are always created on the fly, no cache files used: Performance hit.

### ISSUE THREAD

**Issue by frischnetz** [splittingred/Gallery#70] opened 2011-03-05 02:44 UTC
To check, I installed a fresh version of 2.0.8, installed gallery and uploaded some
pictures. A gallery is created on the frontend. Everything works in principle, but all the
thumbails are on-the-fly generated versions, not cached ones. That is a HUGE
performance hit. 

I did find small automatically-generated thumbnails in /core/cache/phpthumb, but they
are never used.

When I try phpthumbof in comparison, everything works great, the thumbnails that are
displayed indeed are files from the thumbnail-cache (in this case from
/assets/components/phpthumbof/cache).

What I also find strange is that gallery.phpthumb_path points to
/core/components/phpthumb/ while phpthumb is located at core/model/phpthumb/. 
But changing it to the latter does not help.

**Comment by splittingred** [comment] 2011-03-14 16:00
Does this still occur with the latest version of Gallery?

**Comment by frischnetz** [comment] 2011-03-14 16:53
Hi Shaun

Yes, in the frontend and backend as well. I tried version 1.1.0.

The paths for the thumbs are still like this:

http://www.example.com/assets/components/gallery/connector.php?action=web/phpthumb&w=100&h=100&zc=1&far=C&q=90&src=http%3A%2F%2Fwww.example.com%2Fassets%2Fcomponents%2Fgallery%2Ffiles%2F1%2F29.jpg

When I try the phpthumbof-modifier as suggested here: http://modxcms.com/forums/index.php/topic,56411.msg351696.html#msg351696

I get 
http://www.example.com/assets/components/phpthumbof/cache/_assets_components_gallery_files_1_29.jpg.05dda00f0de4d0a2611fe64d7fcf77f6.png

Just to make sure I did not mess up the setting:
gallery.phpthumb_path
/www/htdocs/w006e701/modx-2.0.8-test/core/components/phpthumb/

gallery.phpthumb_url
/core/components/phpthumb/

let me know if you need more info.
Thanks for looking into it.
Jörg

**Comment by nd2s** [comment] 2011-03-15 17:26
I can confirm this.

It is working with phpthumbof, but I've got the problem that I'm using gallerific. I don't know where to place the phpthumbof call for the main image which is placed somehow by js...

**Comment by 1pxrgba** [comment] 2011-03-16 01:03
An example where this seems to be (may be) having a problem is here:
http://modxrules.com/new/demo/jail-modx-revolution-photo-gallery.html?galAlbum=1

If you open up an image inside the colorbox, click forward once and then back once (to where you were) it appears to be re-creating the image each time and the large image appears to never load from phpthumbof's cache but regenerates causing high CPU usage and additional downloading.

**Comment by splittingred** [comment] 2011-03-16 13:44
gallery.phpthumb_path and gallery.phpthumb_url are deprecated and no longer in use...hrm. Will look into it.

**Comment by splittingred** [comment] 2011-03-16 13:46
Ok, so it's definitely caching files; the URL might be the connector.php file, but it's outputting from that, and loading the file from cache within that file. phpThumbOf works differently; it stores cache files on the local server (this is not optimal for Gallery, due to the way galleries work).

So I can confirm caching works on Gallery. Closing ticket. If you're still having issues, check to make sure your PHP install has ImageMagick enabled.

**Closed as completed by splittingred** 2011-03-16 13:46 UTC

**Comment by frischnetz** [comment] 2011-03-16 14:21
Image Magick 2.2.2 is installed.

Yet, I see a noticeable performance difference when comparing gallery with phpthumbof 
and "plain" use:

Plain gallery: http://modx2.frischnetz.de/
phpThumbOf Gallery: http://modx2.frischnetz.de/23.html

If you would like to check it, I could give you manager-access to my demo-site. Just send me a PM for passwords

Jörg
